name: Build Client Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build client image
        run: |
          docker build -t angular_client:latest ./client

      - name: Docker Compose Build (Client Only)
        run: |
          docker-compose build client
